require: rubocop-rails

AllCops:
  Exclude:
    - db/schema.rb
    - bin/*
    - vendor/bundle/**/*
    - node_modules/**/*

Style/Documentation:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false
