version: '3'

services:
  app:
    image: cannapi-app
    container_name: cannapi-app
    env_file: .env
    build: .
    command: bin/dev
    volumes:
      - .:/var/artemis/app
    depends_on:
      - db
      - migrate
    links:
      - db
      - redis
    environment:
      WAIT_HOSTS: db:5432,redis:6379
    labels:
      - 'traefik.enable=true'
      - 'traefik.backend=api'
      - 'traefik.port=3000'
      - 'traefik.frontend.entryPoints=http'
      - 'traefik.frontend.rule=PathPrefix:/'
    stdin_open: true
    tty: true

  sidekiq:
    build: .
    image: cannapi-app
    container_name: cannapi-sidekiq
    env_file: .env
    entrypoint: bin/dev-sidekiq
    volumes:
      - .:/var/artemis/app
    environment:
      WAIT_HOSTS: app:3000
    depends_on:
      - app

  migrate:
    build: .
    image: cannapi-app
    container_name: cannapi-app-migration
    env_file: .env
    entrypoint: bin/dev-migrate
    volumes:
      - .:/var/artemis/app
    environment:
      WAIT_HOSTS: db:5432
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres:11
    container_name: cannapi-db
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - ./db/.data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: cannapi-queue

  traefik:
    image: traefik:1.7.18
    container_name: cannapi-traefik
    command: --web --docker --docker.domain=docker.localhost --logLevel=INFO --docker.exposedbydefault=false
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
